<a href="https://colab.research.google.com/github/rishita999s/DA-Projects/blob/main/MovieRecomendationSystem.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
data=pd.read_csv('drive/MyDrive/Movies1.csv')

In [4]:
data.head()

index      budget    genres       id language    original_title  \
0     NaN         NaN       NaN      NaN      NaN               NaN   
1   603.0  70000000.0  Thriller  11258.0       en         Hard Rain   
2   936.0  50000000.0  Thriller  12103.0       en  Don't Say a Word   
3   943.0  45000000.0  Thriller   9754.0       en          Firewall   
4  1346.0  42000000.0  Thriller   2155.0       en    Reindeer Games   

  popularity                               production_companies release_date  \
0        NaN                                                NaN          NaN   
1  10.930537  [{"name": "Paramount Pictures", "id": 4}, {"na...   1998-01-16   
2  11.596207  [{"name": "Village Roadshow Pictures", "id": 7...   2001-09-28   
3  18.186026  [{"name": "Village Roadshow Pictures", "id": 7...   2006-02-10   
4  11.470135  [{"name": "Dimension Films", "id": 7405}, {"na...   2000-02-25   

     revenue vote_average vote_count            director  
0        NaN          NaN        NaN                 NaN  
1   19870567          5.5        179      Mikael Salomon  
2  100020092            6        220         Gary Fleder  
3   82800000          5.6        267   Richard Loncraine  
4   32168970          5.4        173  John Frankenheimer

In [5]:
data.drop(['index'], axis=1)

budget                          genres        id language  \
0            NaN                             NaN       NaN      NaN   
1     70000000.0                        Thriller   11258.0       en   
2     50000000.0                        Thriller   12103.0       en   
3     45000000.0                        Thriller    9754.0       en   
4     42000000.0                        Thriller    2155.0       en   
...          ...                             ...       ...      ...   
1480         0.0            Thriller Crime Drama  366967.0       en   
1481         0.0        Science Fiction Thriller   86304.0       en   
1482      7000.0  Science Fiction Drama Thriller   14337.0       en   
1483         0.0                Foreign Thriller   67238.0       en   
1484    220000.0           Action Crime Thriller    9367.0       es   

                original_title popularity  \
0                          NaN        NaN   
1                    Hard Rain  10.930537   
2             Don't Say a Word  11.596207   
3                     Firewall  18.186026   
4               Reindeer Games  11.470135   
...                        ...        ...   
1480               Dutch Kills   0.038143   
1481  All Superheroes Must Die   3.545991   
1482                    Primer  23.307949   
1483                    Cavite   0.022173   
1484               El Mariachi  14.269792   

                                   production_companies release_date  \
0                                                   NaN          NaN   
1     [{"name": "Paramount Pictures", "id": 4}, {"na...   1998-01-16   
2     [{"name": "Village Roadshow Pictures", "id": 7...   2001-09-28   
3     [{"name": "Village Roadshow Pictures", "id": 7...   2006-02-10   
4     [{"name": "Dimension Films", "id": 7405}, {"na...   2000-02-25   
...                                                 ...          ...   
1480                                                 []   2015-10-02   
1481               [{"name": "Grindfest", "id": 18818}]   2011-10-26   
1482                 [{"name": "Thinkfilm", "id": 446}]   2004-10-08   
1483                                                 []   2005-03-12   
1484           [{"name": "Columbia Pictures", "id": 5}]   1992-09-04   

        revenue vote_average vote_count            director  
0           NaN          NaN        NaN                 NaN  
1      19870567          5.5        179      Mikael Salomon  
2     100020092            6        220         Gary Fleder  
3      82800000          5.6        267   Richard Loncraine  
4      32168970          5.4        173  John Frankenheimer  
...         ...          ...        ...                 ...  
1480          0            0          0     Joseph Mazzella  
1481          0          4.2         13         Jason Trost  
1482     424760          6.9        658       Shane Carruth  
1483          0          7.5          2    Neill Dela Llana  
1484    2040920          6.6        238    Robert Rodriguez  

[1485 rows x 12 columns]

In [6]:
data.shape

(1485, 13)

In [7]:
data.drop(['id', 'index'], axis=1)

budget                          genres language  \
0            NaN                             NaN      NaN   
1     70000000.0                        Thriller       en   
2     50000000.0                        Thriller       en   
3     45000000.0                        Thriller       en   
4     42000000.0                        Thriller       en   
...          ...                             ...      ...   
1480         0.0            Thriller Crime Drama       en   
1481         0.0        Science Fiction Thriller       en   
1482      7000.0  Science Fiction Drama Thriller       en   
1483         0.0                Foreign Thriller       en   
1484    220000.0           Action Crime Thriller       es   

                original_title popularity  \
0                          NaN        NaN   
1                    Hard Rain  10.930537   
2             Don't Say a Word  11.596207   
3                     Firewall  18.186026   
4               Reindeer Games  11.470135   
...                        ...        ...   
1480               Dutch Kills   0.038143   
1481  All Superheroes Must Die   3.545991   
1482                    Primer  23.307949   
1483                    Cavite   0.022173   
1484               El Mariachi  14.269792   

                                   production_companies release_date  \
0                                                   NaN          NaN   
1     [{"name": "Paramount Pictures", "id": 4}, {"na...   1998-01-16   
2     [{"name": "Village Roadshow Pictures", "id": 7...   2001-09-28   
3     [{"name": "Village Roadshow Pictures", "id": 7...   2006-02-10   
4     [{"name": "Dimension Films", "id": 7405}, {"na...   2000-02-25   
...                                                 ...          ...   
1480                                                 []   2015-10-02   
1481               [{"name": "Grindfest", "id": 18818}]   2011-10-26   
1482                 [{"name": "Thinkfilm", "id": 446}]   2004-10-08   
1483                                                 []   2005-03-12   
1484           [{"name": "Columbia Pictures", "id": 5}]   1992-09-04   

        revenue vote_average vote_count            director  
0           NaN          NaN        NaN                 NaN  
1      19870567          5.5        179      Mikael Salomon  
2     100020092            6        220         Gary Fleder  
3      82800000          5.6        267   Richard Loncraine  
4      32168970          5.4        173  John Frankenheimer  
...         ...          ...        ...                 ...  
1480          0            0          0     Joseph Mazzella  
1481          0          4.2         13         Jason Trost  
1482     424760          6.9        658       Shane Carruth  
1483          0          7.5          2    Neill Dela Llana  
1484    2040920          6.6        238    Robert Rodriguez  

[1485 rows x 11 columns]

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
relevant_features= ['genres', 'production_companies', 'director']

In [10]:
for features in relevant_features:
  data[features]=data[features].fillna('')

In [11]:
combined_features = data['genres'] + ' ' + data['production_companies'] + ' ' + data['director']

In [12]:
print(combined_features)

0                                                        
1       Thriller [{"name": "Paramount Pictures", "id":...
2       Thriller [{"name": "Village Roadshow Pictures"...
3       Thriller [{"name": "Village Roadshow Pictures"...
4       Thriller [{"name": "Dimension Films", "id": 74...
                              ...                        
1480              Thriller Crime Drama [] Joseph Mazzella
1481    Science Fiction Thriller [{"name": "Grindfest"...
1482    Science Fiction Drama Thriller [{"name": "Thin...
1483                 Foreign Thriller [] Neill Dela Llana
1484    Action Crime Thriller [{"name": "Columbia Pict...
Length: 1485, dtype: object


In [13]:
vectorizer=TfidfVectorizer()

In [14]:
feature_vectors=vectorizer.fit_transform(combined_features)

In [15]:
print(feature_vectors)

  (1, 5157)	0.19676391555322004
  (1, 4491)	0.16836082938040492
  (1, 1660)	0.19676391555322004
  (1, 5446)	0.11626832621742927
  (1, 5386)	0.19676391555322004
  (1, 1495)	0.19676391555322004
  (1, 5540)	0.13855991072318707
  (1, 2585)	0.1399577432075898
  (1, 3002)	0.08924180259512135
  (1, 2730)	0.1609232112338538
  (1, 2728)	0.1446714123902444
  (1, 921)	0.18628118154008805
  (1, 4854)	0.18628118154008805
  (1, 5764)	0.18628118154008805
  (1, 1957)	0.17884356339353694
  (1, 5585)	0.17884356339353694
  (1, 4935)	0.16836082938040492
  (1, 3404)	0.17884356339353694
  (1, 5757)	0.17884356339353694
  (1, 5532)	0.17884356339353694
  (1, 1467)	0.1730744985630595
  (1, 4382)	0.1730744985630595
  (1, 350)	0.17884356339353694
  (1, 3315)	0.05480173620785109
  (1, 3425)	0.15787809536727293
  :	:
  (1481, 5567)	0.0770864855656284
  (1482, 2813)	0.5037241367702465
  (1482, 1429)	0.47688788416310224
  (1482, 5243)	0.4578472599207734
  (1482, 5558)	0.4578472599207734
  (1482, 3410)	0.1833662005033

In [16]:
from sklearn.metrics.pairwise import cosine_similarity

In [17]:
similarity=cosine_similarity(feature_vectors)
print(similarity)

[[0.         0.         0.         ... 0.         0.         0.        ]
 [0.         1.         0.14231485 ... 0.03618311 0.00239831 0.06605262]
 [0.         0.14231485 1.         ... 0.03858905 0.00322896 0.09563811]
 ...
 [0.         0.03618311 0.03858905 ... 1.         0.00613978 0.02484468]
 [0.         0.00239831 0.00322896 ... 0.00613978 1.         0.00977007]
 [0.         0.06605262 0.09563811 ... 0.02484468 0.00977007 1.        ]]


In [18]:
print(similarity.shape)

(1485, 1485)


In [19]:
movie_name=str(input('Enter the movie name: '))

Enter the movie name: The Conjuring 


In [20]:
list_of_all_movies=str(data['original_title'])
print(list_of_all_movies)

0                            NaN
1                      Hard Rain
2               Don't Say a Word
3                       Firewall
4                 Reindeer Games
                  ...           
1480                 Dutch Kills
1481    All Superheroes Must Die
1482                      Primer
1483                      Cavite
1484                 El Mariachi
Name: original_title, Length: 1485, dtype: object


In [21]:
import numpy as np
import difflib

In [22]:
numpy_array=np.array(list(list_of_all_movies))

In [23]:
closest_match = difflib.get_close_matches(movie_name, list_of_all_movies, cutoff=0.0000000007)
print(closest_match)

['u', 'u', 'u']


In [24]:
close_match=closest_match[0]
print(close_match)

u


In [25]:
index_of_the_movie = data[data.original_title == close_match]['index'].values
print(index_of_the_movie)


[]


In [26]:
index_of_the_movie=0
similarity_score=list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 0.0), (38, 0.0), (39, 0.0), (40, 0.0), (41, 0.0), (42, 0.0), (43, 0.0), (44, 0.0), (45, 0.0), (46, 0.0), (47, 0.0), (48, 0.0), (49, 0.0), (50, 0.0), (51, 0.0), (52, 0.0), (53, 0.0), (54, 0.0), (55, 0.0), (56, 0.0), (57, 0.0), (58, 0.0), (59, 0.0), (60, 0.0), (61, 0.0), (62, 0.0), (63, 0.0), (64, 0.0), (65, 0.0), (66, 0.0), (67, 0.0), (68, 0.0), (69, 0.0), (70, 0.0), (71, 0.0), (72, 0.0), (73, 0.0), (74, 0.0), (75, 0.0), (76, 0.0), (77, 0.0), (78, 0.0), (79, 0.0), (80, 0.0), (81, 0.0), (82, 0.0), (83, 0.0), (84, 0.0), (85, 0.0), (86, 0.0), (87, 0.0), (88, 0.0), (89, 0.0), (90, 0.0), (91, 0.0

In [27]:
len(similarity_score)

1485

In [28]:
sort_similar_movies = sorted(similarity_score, key = lambda x:x[1], reverse = True)
print(sort_similar_movies)

[(0, 0.0), (1, 0.0), (2, 0.0), (3, 0.0), (4, 0.0), (5, 0.0), (6, 0.0), (7, 0.0), (8, 0.0), (9, 0.0), (10, 0.0), (11, 0.0), (12, 0.0), (13, 0.0), (14, 0.0), (15, 0.0), (16, 0.0), (17, 0.0), (18, 0.0), (19, 0.0), (20, 0.0), (21, 0.0), (22, 0.0), (23, 0.0), (24, 0.0), (25, 0.0), (26, 0.0), (27, 0.0), (28, 0.0), (29, 0.0), (30, 0.0), (31, 0.0), (32, 0.0), (33, 0.0), (34, 0.0), (35, 0.0), (36, 0.0), (37, 0.0), (38, 0.0), (39, 0.0), (40, 0.0), (41, 0.0), (42, 0.0), (43, 0.0), (44, 0.0), (45, 0.0), (46, 0.0), (47, 0.0), (48, 0.0), (49, 0.0), (50, 0.0), (51, 0.0), (52, 0.0), (53, 0.0), (54, 0.0), (55, 0.0), (56, 0.0), (57, 0.0), (58, 0.0), (59, 0.0), (60, 0.0), (61, 0.0), (62, 0.0), (63, 0.0), (64, 0.0), (65, 0.0), (66, 0.0), (67, 0.0), (68, 0.0), (69, 0.0), (70, 0.0), (71, 0.0), (72, 0.0), (73, 0.0), (74, 0.0), (75, 0.0), (76, 0.0), (77, 0.0), (78, 0.0), (79, 0.0), (80, 0.0), (81, 0.0), (82, 0.0), (83, 0.0), (84, 0.0), (85, 0.0), (86, 0.0), (87, 0.0), (88, 0.0), (89, 0.0), (90, 0.0), (91, 0.0

In [29]:
print('Movies suggested for you: \n')
i = 1

for movies in sort_similar_movies:
    index = movies[0]
    title_from_index = data[data.index==index]['original_title'].values[0]
    if(i<30):
        print(i,'.',title_from_index)
        i+=1

Movies suggested for you: 

1 . nan
2 . Hard Rain
3 . Don't Say a Word
4 . Firewall
5 . Reindeer Games
6 . Assault on Precinct 13
7 . Money Monster
8 . Our Kind of Traitor
9 . Survivor
10 . Red Lights
11 . City of Ghosts
12 . A Most Wanted Man
13 . The In Crowd
14 . Mientras duermes
15 . The Boy Next Door
16 . Enter the Dangerous Mind
17 . AWOL-72
18 . The Calling
19 . Plush
20 . $upercapitalist
21 . Shark Lake
22 . Chocolate: Deep Dark Secrets
23 . The Maid's Room
24 . Straightheads
25 . The Tooth Fairy
26 . The Conjuring 2
27 . The Reaping
28 . A Nightmare on Elm Street
29 . Poltergeist
